using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Forms;

namespace CK3MPS
{
    internal sealed partial class MainForm
    {
        private string scanSettingsExportReportText = "";

        private void ConfigureScanExportRuntimeFix()
        {
            checkButton.Text = "Scan Settings";
            exportScanReportButton.Text = "Scan Export";
            ReplaceClickHandlers(checkButton, delegate { RunScanSettingsAndCaptureExport(); });
            ReplaceClickHandlers(exportScanReportButton, delegate { ExportCapturedScanSettingsReport(); });
            exportScanReportButton.Enabled = !busyUi && !String.IsNullOrWhiteSpace(scanSettingsExportReportText);
        }

        private async void RunScanSettingsAndCaptureExport()
        {
            bool previousLiveLogWritesEnabled = liveLogWritesEnabled;
            try
            {
                scanSettingsExportReportText = "";
                exportScanReportButton.Enabled = false;
                liveLogWritesEnabled = false;
                liveLogBuffer.Length = 0;
                await RunCheckOnlyAsync();
            }
            finally
            {
                liveLogWritesEnabled = previousLiveLogWritesEnabled;
                liveLogBuffer.Length = 0;
                CaptureScanSettingsExportReport();
                exportScanReportButton.Enabled = !busyUi && !String.IsNullOrWhiteSpace(scanSettingsExportReportText);
                if (exportScanReportButton.Enabled)
                    SetStatusText("Scan complete. Scan Export is now available.");
            }
        }

        private void CaptureScanSettingsExportReport()
        {
            string[] runLogLines = SnapshotRunLogLines();
            if (runLogLines == null || runLogLines.Length == 0)
                runLogLines = new[] { "ERROR Scan did not produce a log snapshot." };

            int failures = Math.Max(0, lastReadinessFailures);
            scanSettingsExportReportText = BuildScanSettingsExportReportText(failures, runLogLines);
            lastCheckOnlyReportText = scanSettingsExportReportText;
        }

        private string BuildScanSettingsExportReportText(int readinessFailures, string[] runLogLines)
        {
            StringBuilder sb = new StringBuilder();
            HashSet<string> emitted = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            sb.AppendLine("CK3MPS compact check");
            sb.AppendLine("Stabilizer: " + AppVersion);
            sb.AppendLine("Generated: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            sb.AppendLine("Result: " + (readinessFailures == 0 ? "READY" : "NOT READY"));
            sb.AppendLine("Failed readiness checks: " + readinessFailures);
            sb.AppendLine();

            foreach (string line in runLogLines ?? new string[0])
            {
                string trimmed = (line ?? "").Trim();
                if (!IsImportantScanExportLine(trimmed))
                    continue;

                string normalized = NormalizeScanExportLine(trimmed, readinessFailures);
                if (String.IsNullOrWhiteSpace(normalized))
                    continue;

                if (!emitted.Add(normalized))
                    continue;

                sb.AppendLine(normalized);
            }

            return sb.ToString();
        }

        private bool IsImportantScanExportLine(string line)
        {
            if (String.IsNullOrWhiteSpace(line))
                return false;
            return line.StartsWith("FAIL", StringComparison.OrdinalIgnoreCase)
                || line.StartsWith("WARN", StringComparison.OrdinalIgnoreCase)
                || line.StartsWith("RESULT", StringComparison.OrdinalIgnoreCase);
        }

        private string NormalizeScanExportLine(string line, int readinessFailures)
        {
            if (line.IndexOf("Host suitability report is up to date", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                if (readinessFailures == 0)
                    return "WARN  | Host suitability report can be regenerated by Apply Settings; this is advisory and not a final readiness blocker.";
                return line;
            }

            if (line.IndexOf("Critical host-save rules are confirmed safe", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return "WARN  | Critical host-save rules are not confirmed safe for the current recommended save. Use Workflow > Fix save + host or choose a known clean manual local save before hosting.";
            }

            return line;
        }

        private void ExportCapturedScanSettingsReport()
        {
            if (String.IsNullOrWhiteSpace(scanSettingsExportReportText))
            {
                MessageBox.Show("Run Scan Settings before exporting its report.", "Scan Export", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            using (SaveFileDialog dialog = new SaveFileDialog())
            {
                dialog.Title = "Scan Export";
                dialog.Filter = "Text report (*.txt)|*.txt|All files (*.*)|*.*";
                dialog.FileName = "CK3MPS_scan_settings_" + DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".txt";
                if (dialog.ShowDialog(this) != DialogResult.OK)
                    return;

                SafeAtomicFile.WriteAllText(dialog.FileName, scanSettingsExportReportText, Encoding.UTF8);
                SetStatusText("Scan report exported: " + dialog.FileName);
            }
        }
    }
}
